
title: My Resume
url: 'http://saytosid.github.io'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
# style: styles-4
style: styles-5
# style: styles-6


#Profile information
name: Siddhant Kumar
tagline: Software Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: saytosid@gmail.com
phone: +44-7340183464
website: saytosid.github.io #do not add http://
linkedin: saytosid
github: saytosid
twitter: '@saytosid'


# Tracker
analytics: UA-99817065-1
#Update all the sections by editing the files inside _includes folder.
